const stockPaths = [
  "static/stock_512/xps-EzYq1HOl5_8-unsplash.jpg",
  "static/stock_512/toa-heftiba-O3ymvT7Wf9U-unsplash.jpg",
  "static/stock_512/timon-studler-ABGaVhJxwDQ-unsplash.jpg",
  "static/stock_512/toa-heftiba-6bKpHAun4d8-unsplash.jpg",
  "static/stock_512/simon-abrams-k_T9Zj3SE8k-unsplash.jpg",
  "static/stock_512/tamara-bitter-Xn4g9aHY4ao-unsplash.jpg",
  "static/stock_512/okai-vehicles-AA0UcHfbd1Q-unsplash.jpg",
  "static/stock_512/priscilla-du-preez-XkKCui44iM0-unsplash.jpg",
  "static/stock_512/nicolo-canu-mbu_MpTNCQE-unsplash.jpg",
  "static/stock_512/nathan-dumlao-p4TKmK4Egvg-unsplash.jpg",
  "static/stock_512/michael-dam-mEZ3PoFGs_k-unsplash.jpg",
  "static/stock_512/mauro-mora-31-pOduwZGE-unsplash.jpg",
  "static/stock_512/marvin-meyer-SYTO3xs06fU-unsplash.jpg",
  "static/stock_512/lagostechie-IgUR1iX0mqM-unsplash.jpg",
  "static/stock_512/josh-miller-CpZzU7w4Cz4-unsplash.jpg",
  "static/stock_512/hugo-sesma-5-k1lJ78MKg-unsplash.jpg",
  "static/stock_512/eddy-klaus-BHNxfaeNCTI-unsplash.jpg",
  "static/stock_512/christopher-burns-8KfCR12oeUM-unsplash.jpg",
  "static/stock_512/arno-senoner-JwPtiCaFV6M-unsplash.jpg",
  "static/stock_512/alex-kotliarskyi-QBpZGqEMsKg-unsplash.jpg",

  "static/misc/bitmap@2x.jpg",
  "static/misc/bitmap_2.jpg",
  "static/misc/screen-shot-2020-04-02-at-3-04-34-pm.jpg",
  "static/misc/bitmap_3.jpg",
  "static/misc/bitmap_10.jpg",
  "static/misc/bitmap_4.jpg",
  "static/misc/img-corindus-04_3.jpg",
  "static/misc/bitmap_6.jpg",
  "static/misc/top-outpatient-procedures-asc-hospital.jpg",
  "static/misc/bitmap_9.jpg",
  "static/misc/img-corindus-04_2.jpg",
  "static/misc/img-corindus-04.jpg",
  "static/misc/climate-protection-media-cta.jpg",
  "static/misc/bitmap_8.jpg",
  "static/misc/bitmap_11.jpg",
  "static/misc/bitmap_7.jpg",
  "static/misc/5-g-labs-marquee-logo-1018-x-600.jpg",
];

export default stockPaths;
